// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4uQoWCbYPu_DvmHpYdHAOoXVEfD-GfE',
    appId: '1:194800434113:web:06c7166770ef5ea0c40d40',
    messagingSenderId: '194800434113',
    projectId: 'todolistapp-7b3c8',
    authDomain: 'todolistapp-7b3c8.firebaseapp.com',
    storageBucket: 'todolistapp-7b3c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASeUpAAZZHZnmKhN_lJdpXttAyTRIFUec',
    appId: '1:194800434113:android:62f82d0ede634d5cc40d40',
    messagingSenderId: '194800434113',
    projectId: 'todolistapp-7b3c8',
    storageBucket: 'todolistapp-7b3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAIXcJji7mo1gIJyaGkdBRoN1a9OUzfjo',
    appId: '1:194800434113:ios:017bd134c35eb5c1c40d40',
    messagingSenderId: '194800434113',
    projectId: 'todolistapp-7b3c8',
    storageBucket: 'todolistapp-7b3c8.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAIXcJji7mo1gIJyaGkdBRoN1a9OUzfjo',
    appId: '1:194800434113:ios:017bd134c35eb5c1c40d40',
    messagingSenderId: '194800434113',
    projectId: 'todolistapp-7b3c8',
    storageBucket: 'todolistapp-7b3c8.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4uQoWCbYPu_DvmHpYdHAOoXVEfD-GfE',
    appId: '1:194800434113:web:bd97a49be53c6a12c40d40',
    messagingSenderId: '194800434113',
    projectId: 'todolistapp-7b3c8',
    authDomain: 'todolistapp-7b3c8.firebaseapp.com',
    storageBucket: 'todolistapp-7b3c8.appspot.com',
  );
}
